#!/bin/bash
### BEGIN INIT INFO
# Provides:          doorjam_watchdog
# Required-Start:    $remote_fs $syslog doorjam
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: psy running 
# Description:       doorjam_watchdog is a hardware watchdog daemon for doorjam
### END INIT INFO
#
# initd a node app
# Based on a script posted by https://gist.github.com/jinze at https://gist.github.com/3748766
#

HOME=/root

# Source function library.
. /lib/lsb/init-functions

logFile="/var/log/doorjam_watchdog.log"
appName="doorjam watchdog"
command="/usr/local/bin/node"
nodeApp="/opt/doorjam/bin/watchdog.js"
runnerApp="/usr/local/bin/psy"
workingDir="/opt/doorjam"

start() {
	echo "Starting $nodeApp"

	# Notice that we change the PATH because on reboot
  # the PATH does not include the path to node.
  PATH=/usr/local/bin:$PATH
  export NODE_ENV=production
  #PORT=80
  cd $workingDir
  $runnerApp start --logfile $logFile --name doorjam -- node $nodeApp
  RETVAL=$?
}

restart() {
	echo -n "Restarting $appName"
	$runnerApp restart doorjam
	RETVAL=$?
}

stop() {
  echo -n "Shutting down $appName"
  $runnerApp stop doorjam
  RETVAL=$?
}

status() {
  echo -n "Status $appName"
  $runnerApp list
  RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        stop
        ;;
   status)
        status
       ;;
   restart)
   	restart
        ;;
	*)
       echo "Usage:  {start|stop|status|restart}"
       exit 1
        ;;
esac
exit $RETVAL
